### ISSUE TITLE
文档里uses的name是错的

### ISSUE THREAD

**Issue by helloint** [echoings/actions.mini-program#6]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
文档里的例子，uses的name错了，应该是：
```
      - name: actions.mini-program
        uses: echoings/actions.mini-program@main
```
不知道是不是这两年调整过

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
还有就是看源码发现`remark`可以设置上传版本的`desc`
```
      - name: actions.mini-program
        uses: echoings/actions.mini-program@main
        with:
          project_type: miniProgram
          action_type: upload
          project_path: ./dist
          remark: ${{ github.event.inputs.desc }}
```
不传的话，就还是默认值
